#!/usr/bin/env python

# -*- coding: utf-8 -*-
import re
import sys

from pyconfirmdeployment.confirm import run_pyconfirmdeployment

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(run_pyconfirmdeployment())